kind: pipeline
type: docker
name: default

steps:
- name: semgrep
  image: returntocorp/semgrep:latest
  commands:
    - git fetch origin master
    - semgrep ci  
  environment:
    SEMGREP_APP_TOKEN:
      from_secret: SEMGREP_APP_TOKEN
