on:
  pull_request: {}
  push:
    branches:
    - master
    paths:
    - .github/workflows/semgrep.yml
name: Semgrep
jobs:
  my_first_job: 
    name: requirementsGeneration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate requirements txt
        run: pip freeze --all | tee requirements.txt
      - name: Upload Requirements File as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: requirementstxt
          path: requirements.txt

